Resources:
  ModaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true 
      Tags:
        - Key: Name
          Value: ModaVpc
  ModaInternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ModaVPC
      InternetGatewayId: !Ref ModaInternetGateway
  ModaRouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ModaVPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref ModaRouteTablePublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref ModaInternetGateway
  ModaNetworkACL:
      Type: AWS::EC2::NetworkAcl
      Properties:
        VpcId: !Ref ModaVPC
  ModaSGPublic:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !Ref ModaVPC
      GroupDescription: Enable SSH and HTTP inbound rule
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Join [" ", [Public, SecurityGroup, !Ref AWS::Region ] ]     
  ModaSGPrivate:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !Ref ModaVPC
      GroupDescription: Enable SSH and HTTP inbound rule
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !GetAtt ModaSubnetPublic.CidrBlock
      Tags:
        - Key: Name
          Value: !Join [" ", [Private, SecurityGroup, !Ref AWS::Region ] ]      
  ModaSubnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref ModaVPC
      AvailabilityZone: !Select [0, !GetAZs ] 
      Tags:
        - Key: Name
          Value: !Join [" ", [Public, Subnet, !Ref AWS::Region ] ]
  ModaSubnetPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref ModaVPC
      AvailabilityZone: !Select [0, !GetAZs ]
      Tags: 
        - Key: Name
          Value: PrivateSubnet
  ModaCustomer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: Moda
      ImageId: ami-0005e0cfe09cc9050
      SecurityGroupIds:
        - !Ref ModaSGPublic
      SubnetId: !Ref ModaSubnetPublic
      Tags: 
        - Key: Name
          Value: !Join [" ", [Customer, Instance, !Ref AWS::Region ]]
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0 
  ModaAdmin:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: Moda
      ImageId: ami-0005e0cfe09cc9050
      SecurityGroupIds:
        - !Ref ModaSGPrivate
      SubnetId: !Ref ModaSubnetPrivate
      Tags:
        - Key: Name # use K in capital letter 
          Value: !Join [" ", [Admin, Instance, !Ref AWS::Region ]]
      NetworkInterfaces:
      - AssociatePublicIpAddress: true  # Add this line
        DeviceIndex: 0    