Resources:
  ModaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: VPC
  ModaSGPublic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref ModaVPC
      GroupDescription: Enable HTTP and SSH from port 80 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80 
      Tags:
        - Key: Name
          Value: !Join [" ", [Public, SecurityGroup, !Ref AWS::Region ] ]     
  ModaSGPrivate:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref ModaVPC
      GroupDescription: Enable HTTP and SSH from port 80 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort 22
          ToPort: 22
          CidrIp: !GetAtt ModaPublicSubnet.CidrBlock
      Tags:
        - Key: Name
          Value: !Join [" ", [Private, SecurityGroup, !Ref AWS::Region ] ]    

  ModaPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref ModaVPC
      AvailabilityZone: !Select (0, !GetAZs )
      Tags: 
        - Key: Name
          Value: PublicSubnet
  ModaPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref ModaVPC
      AvailabilityZone: !Select (0, !GetAZs )
      Tags: 
        - Key: Name
          Value: PublicSubnet
  AdminInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: Moda
      InstanceType: t2.micro
      ImageId: ami-0005e0cfe09cc9050
      SecurityGroupIds:
        - !Ref ModaSGPrivate
      SubnetId: !Ref ModaPrivateSubnet
      Tags:
        - Key: Name
          Value: !Join [" ", [Admin, Instance, Ref! AWS::Region ] ] 
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0 
  CustomerInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: Moda
      InstanceType: t2.micro
      ImageId: ami-0005e0cfe09cc9050
      SecurityGroupIds:
        - !Ref ModaSGPublic
      SubnetId: !Ref ModaPublicSubnet
      Tags:
        - Key: Name
          Value: !Join [" ", [Customer, Instance, Ref! AWS::Region ] ] 
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0 
